Warning in '__main__.test_Notices' at line 111 in some file 'Warning 1'
-- sourceLocation: testTfPyDiagnosticNotices:111 - __main__.test_Notices
-- commentary: Warning 1
-- diagnosticCode: Tf.TF_DIAGNOSTIC_WARNING_TYPE (TF_DIAGNOSTIC_WARNING_TYPE)
Warning in '__main__.test_Notices' at line 112 in some file 'Warning 2'
-- sourceLocation: testTfPyDiagnosticNotices:112 - __main__.test_Notices
-- commentary: Warning 2
-- diagnosticCode: Tf.TF_DIAGNOSTIC_WARNING_TYPE (TF_DIAGNOSTIC_WARNING_TYPE)
Warning in '__main__.test_Notices' at line 113 in some file 'Warning 3'
-- sourceLocation: testTfPyDiagnosticNotices:113 - __main__.test_Notices
-- commentary: Warning 3
-- diagnosticCode: Tf.TF_DIAGNOSTIC_WARNING_TYPE (TF_DIAGNOSTIC_WARNING_TYPE)
Status in '__main__.test_Notices' at line 116 in some file Almost done testing.'
-- sourceLocation: testTfPyDiagnosticNotices:116 - __main__.test_Notices
-- commentary: Status: Almost done testing.
-- diagnosticCode: Tf.TF_DIAGNOSTIC_STATUS_TYPE (TF_DIAGNOSTIC_STATUS_TYPE)
